## Numpy 

Numpy is a fundamental library for scientific computing in Python. It provides support for arrays and matrices, along with a collection of mathematical functions to operate on these data sstrructures. In this lesson, we will cover the basics of Numpy, focusing on arrays and vectorized operations. 

In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip available: 22.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import numpy as np

##create an array using numpy
##create 1D array
arr1=np.array([1,2,3,4,5,6])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5 6]
<class 'numpy.ndarray'>
(6,)


In [3]:
## Reshaping to 2D
arr2=np.array([1,2,3,4,5])
arr2.reshape(1,5)

array([[1, 2, 3, 4, 5]])

In [4]:
arr2=np.array([[1,2,3,4,5]])
arr2.shape

(1, 5)

In [ ]:
##2D array
arr2=np.array([[1,2,3,4,5],[2,3,4,5,6]])
print(arr2)
print(arr2.shape)

[[1 2 3 4 5]
 [2 3 4 5 6]]
(2, 5)


In [8]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [ ]:
##Convert to 2D array
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [10]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [11]:
## Identity Matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [13]:
##Atributes of Numpy
arr=np.array([[1,2,3],[4,5,6]])

print("Array:\n",arr)
print("SShape:",arr.shape)
print("Number of dimension:",arr.ndim)
print("SSize (number of elements):",arr.size)
print("Data Type:",arr.dtype)
print("Item size (in bytes):",arr.itemsize)

Array:
 [[1 2 3]
 [4 5 6]]
SShape: (2, 3)
Number of dimension: 2
SSize (number of elements): 6
Data Type: int64
Item size (in bytes): 8


In [15]:
## Numpy Vectorized Operations
arr1=np.array([1,2,3,4,5])
arr2=np.array([10,20,30,40,50])

##Element wise Addition
print("Addition",arr1+arr2)

##Element wise Substraction
print("Substraction",arr1-arr2)

##Element wise Multiplication
print("Multiplication",arr1*arr2)

##Elemnt wise Division
print("Divison",arr1/arr2)

Addition [11 22 33 44 55]
Substraction [ -9 -18 -27 -36 -45]
Multiplication [ 10  40  90 160 250]
Divison [0.1 0.1 0.1 0.1 0.1]


In [18]:
## Universal Function
arr=np.array([2,3,4,5,6])
## Square Root
print(np.sqrt(arr))

##Exponential
print(np.exp(arr))

##Sine
print(np.sin(arr))

##Natural log
print(np.log(arr))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [19]:
##Array Slicing and Indexing

arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("Array:\n",arr)

Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [20]:
arr[0]

array([1, 2, 3, 4])

In [21]:
arr[0][0]

np.int64(1)

In [23]:
arr[2:]

array([[ 9, 10, 11, 12]])

In [25]:
print(arr[0][0])
print(arr[0:2])

1
[[1 2 3 4]
 [5 6 7 8]]


In [24]:
arr[1:,2:]

array([[ 7,  8],
       [11, 12]])