## Numpy 

Numpy is a fundamental library for scientific computing in Python. It provides support for arrays and matrices, along with a collection of mathematical functions to operate on these data sstrructures. In this lesson, we will cover the basics of Numpy, focusing on arrays and vectorized operations. 

In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip available: 22.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import numpy as np

##create an array using numpy
##create 1D array
arr1=np.array([1,2,3,4,5,6])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5 6]
<class 'numpy.ndarray'>
(6,)


In [3]:
## Reshaping to 2D
arr2=np.array([1,2,3,4,5])
arr2.reshape(1,5)

array([[1, 2, 3, 4, 5]])

In [4]:
arr2=np.array([[1,2,3,4,5]])
arr2.shape

(1, 5)

In [ ]:
##2D array
arr2=np.array([[1,2,3,4,5],[2,3,4,5,6]])
print(arr2)
print(arr2.shape)

[[1 2 3 4 5]
 [2 3 4 5 6]]
(2, 5)


In [8]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [ ]:
##Convert to 2D array
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [10]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])